[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[module]
  [[module.imports]]
    path = "github.com/digitalcraftsman/hugo-sitemap"


[params]
  sitemap = true

[outputs]
home = ["HTML", "RSS", "SITEMAP"]
