baseURL = 'https://blog.000xs.xyz/'
languageCode = 'en-us'
title = '000xs Blog'

theme = "000x"


[params]
  sitemap = true
  
[module]
  [[module.imports]]
    path = "github.com/digitalcraftsman/hugo-sitemap"

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
