baseURL = 'https://blog.000xs.xyz/'
languageCode = 'en-us'
title = '000xs Blog'

theme = "000x"

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
