name = 'blog 000x'
license = 'MIT'
licenselink = 'https://github.com/000xs/blog.000xs.xyz/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/000xs/blog.000xs.xyz'

# If you have a running demo of the theme
demosite = 'https://blog.000xs.xyz/'

# Taxonomy terms
tags = ['blog', 'personal']
features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'Sithum Sathsara Rajapaksha', homepage = 'Website of author'},
  {name = '000x', homepage = 'Website of author'}
]

# If the theme has a single author
[author]
  name = '000xs Blog'
  homepage = '000xs Blog'

# If porting an existing theme
[original]
  author = '000x'
  homepage = '000x'
  repo = 'https://github.com/000xs/blog.000xs.xyz'
